\ TEMPLATE FILE for STM32F103xx
\ created by svdcutter for Mecrisp-Stellaris Forth by Matthias Koch
\ sdvcutter  takes a CMSIS-SVD file plus a hand edited config.xml file as input 
\ By Terry Porter "terry@tjporter.com.au", released under the GPL V2 Licence
\   Modified by juju2013@github - 2020

0x40006C04 constant BKP ( Backup registers ) 
BKP 0x0 + constant BKP-DR1 ( Backup data register BKP_DR ) 
BKP 0x4 + constant BKP-DR2 ( Backup data register BKP_DR ) 
BKP 0x8 + constant BKP-DR3 ( Backup data register BKP_DR ) 
BKP 0xC + constant BKP-DR4 ( Backup data register BKP_DR ) 
BKP 0x10 + constant BKP-DR5 ( Backup data register BKP_DR ) 
BKP 0x14 + constant BKP-DR6 ( Backup data register BKP_DR ) 
BKP 0x18 + constant BKP-DR7 ( Backup data register BKP_DR ) 
BKP 0x1C + constant BKP-DR8 ( Backup data register BKP_DR ) 
BKP 0x20 + constant BKP-DR9 ( Backup data register BKP_DR ) 
BKP 0x24 + constant BKP-DR10 ( Backup data register BKP_DR ) 
BKP 0x3C + constant BKP-DR11 ( Backup data register BKP_DR ) 
BKP 0x40 + constant BKP-DR12 ( Backup data register BKP_DR ) 
BKP 0x44 + constant BKP-DR13 ( Backup data register BKP_DR ) 
BKP 0x48 + constant BKP-DR14 ( Backup data register BKP_DR ) 
BKP 0x4C + constant BKP-DR15 ( Backup data register BKP_DR ) 
BKP 0x50 + constant BKP-DR16 ( Backup data register BKP_DR ) 
BKP 0x54 + constant BKP-DR17 ( Backup data register BKP_DR ) 
BKP 0x58 + constant BKP-DR18 ( Backup data register BKP_DR ) 
BKP 0x5C + constant BKP-DR19 ( Backup data register BKP_DR ) 
BKP 0x60 + constant BKP-DR20 ( Backup data register BKP_DR ) 
BKP 0x64 + constant BKP-DR21 ( Backup data register BKP_DR ) 
BKP 0x68 + constant BKP-DR22 ( Backup data register BKP_DR ) 
BKP 0x6C + constant BKP-DR23 ( Backup data register BKP_DR ) 
BKP 0x70 + constant BKP-DR24 ( Backup data register BKP_DR ) 
BKP 0x74 + constant BKP-DR25 ( Backup data register BKP_DR ) 
BKP 0x78 + constant BKP-DR26 ( Backup data register BKP_DR ) 
BKP 0x7C + constant BKP-DR27 ( Backup data register BKP_DR ) 
BKP 0x80 + constant BKP-DR28 ( Backup data register BKP_DR ) 
BKP 0x84 + constant BKP-DR29 ( Backup data register BKP_DR ) 
BKP 0x88 + constant BKP-DR30 ( Backup data register BKP_DR ) 
BKP 0x8C + constant BKP-DR31 ( Backup data register BKP_DR ) 
BKP 0x90 + constant BKP-DR32 ( Backup data register BKP_DR ) 
BKP 0x94 + constant BKP-DR33 ( Backup data register BKP_DR ) 
BKP 0x98 + constant BKP-DR34 ( Backup data register BKP_DR ) 
BKP 0x9C + constant BKP-DR35 ( Backup data register BKP_DR ) 
BKP 0xA0 + constant BKP-DR36 ( Backup data register BKP_DR ) 
BKP 0xA4 + constant BKP-DR37 ( Backup data register BKP_DR ) 
BKP 0xA8 + constant BKP-DR38 ( Backup data register BKP_DR ) 
BKP 0xAC + constant BKP-DR39 ( Backup data register BKP_DR ) 
BKP 0xB0 + constant BKP-DR40 ( Backup data register BKP_DR ) 
BKP 0xB4 + constant BKP-DR41 ( Backup data register BKP_DR ) 
BKP 0xB8 + constant BKP-DR42 ( Backup data register BKP_DR ) 
BKP 0x28 + constant BKP-RTCCR ( RTC clock calibration register  BKP_RTCCR ) 
BKP 0x2C + constant BKP-CR ( Backup control register  BKP_CR ) 
BKP 0x30 + constant BKP-CSR ( BKP_CSR control/status register  BKP_CSR ) 
